#!/bin/bash

## This utility script takes a list of packages to install
## and then installs thouse packages.

apt-get update
apt-get install -y $@ --no-install-recommends 
apt-get clean
rm -rf /var/lib/apt/lists/*

exit

